<?php
/*
 You may not change or alter any portion of this comment or credits
 of supporting developers from this source code or any supporting source code
 which is considered copyrighted (c) material of the original comment or credit authors.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

/**
 * @copyright       The XUUPS Project http://sourceforge.net/projects/xuups/
 * @license         http://www.fsf.org/copyleft/gpl.html GNU public license
 * @package         Publisher
 * @since           1.0
 * @author          trabis <lusopoemas@gmail.com>
 * @author          The SmartFactory <www.smartfactory.ca>
 * @version         $Id: xoops_version.php 11345 2013-04-03 22:35:51Z luciorota $
 */

// defined("XOOPS_ROOT_PATH") || die("XOOPS root path not defined");
xoops_load('XoopsLocal');

$modversion['name']        = _MI_PUBLISHER_MD_NAME;
$modversion['version']     = 1.02;
$modversion['description'] = _MI_PUBLISHER_MD_DESC;
$modversion['author']      = "Trabis (www.Xuups.com)";
$modversion['credits']     = "w4z004, hsalazar, Mithrandir, fx2024, Ackbarr, Mariuss, Marco, Michiel, phppp, outch, Xvitry, Catzwolf, Shine, McDonald, trabis, Mowaffak, Bandit-x, Shiva";
$modversion['help']        = 'page=help';
$modversion['license']     = 'GNU GPL 2.0';
$modversion['license_url'] = "www.gnu.org/licenses/gpl-2.0.html/";
$modversion['official']    = 0;
$modversion['dirname']     = basename(__DIR__);

//include_once XOOPS_ROOT_PATH . "/modules/" . $modversion['dirname'] . "/include/constants.php";
xoops_load('constants', basename(__DIR__));

$logo_filename = $modversion['dirname'] . "_logo.png";

if (file_exists(XOOPS_ROOT_PATH . "/modules/" . $modversion['dirname'] . "/assets/images/" . $logo_filename)) {
    $modversion['image'] = "assets/images/{$logo_filename}";
} else {
    $modversion['image'] = "assets/images/module_logo.png";
}
// Install
$modversion['onInstall'] = 'include/install.php';
// Update
$modversion['onUpdate'] = 'include/update.php';

// Added by marcan for the About page in admin section
$modversion['adminMenu']              = "publisher_adminMenu";
$modversion['developer_lead']         = "trabis";
$modversion['developer_website_url']  = "http://www.xuups.com";
$modversion['developer_website_name'] = "Xoops User Utilities";
$modversion['developer_email']        = "lusopoemas@gmail.com";
$modversion['status_version']         = "Final";
$modversion['status']                 = "Beta 1";
$modversion['date']                   = "2011-12-04";

//$modversion['warning'] = _MI_PUBLISHER_WARNING_BETA;

$modversion['demo_site_url']     = "";
$modversion['demo_site_name']    = "";
$modversion['support_site_url']  = "http://www.xuups.com/modules/newbb/viewforum.php?forum=28";
$modversion['support_site_name'] = "Xuups";
$modversion['submit_bug']        = "http://www.xuups.com/modules/newbb/viewforum.php?forum=28";
$modversion['submit_feature']    = "http://www.xuups.com/modules/newbb/viewforum.php?forum=28";

$modversion['people']['developers'][] = "trabis";
$modversion['people']['developers'][] = "Mowaffak";
$modversion['people']['developers'][] = "Bandit-x";
$modversion['people']['developers'][] = "Shiva";

$modversion['people']['testers'][] = "urban, AEIOU, pacho, mariane";
//$modversion['people']['translaters'][] = "";
//$modversion['people']['documenters'][] = "";

$modversion['author_word'] = "";

//about
$modversion["module_status"]  = "Beta 4";
$modversion['release_date']   = "2014/12/12";
$modversion['min_php']        = '5.3.7';
$modversion['min_xoops']      = '2.5.7';
$modversion['min_db']         = array('mysql' => '5.0.7', 'mysqli' => '5.0.7');
$modversion['min_admin']      = '1.1';
$modversion['dirmoduleadmin'] = 'Frameworks/moduleclasses';
$modversion['icons16']        = 'Frameworks/moduleclasses/icons/16';
$modversion['icons32']        = 'Frameworks/moduleclasses/icons/32';

$modversion['author_word'] = "";

// Admin things
$modversion['hasAdmin']    = 1;
$modversion['adminindex']  = "admin/index.php";
$modversion['adminmenu']   = "admin/menu.php";
$modversion['system_menu'] = 1;

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "publisher_categories";
$modversion['tables'][1] = "publisher_items";
$modversion['tables'][2] = "publisher_files";
$modversion['tables'][3] = "publisher_meta";
$modversion['tables'][4] = "publisher_mimetypes";
$modversion['tables'][5] = "publisher_rating";

// Search
$modversion['hasSearch']      = 1;
$modversion['search']['file'] = "include/search.inc.php";
$modversion['search']['func'] = "publisher_search";

// Menu
$modversion['hasMain'] = 1;

global $xoopsModule;
if (is_object($xoopsModule) && $xoopsModule->getVar('dirname') == $modversion['dirname']) {
    global $xoopsModuleConfig, $xoopsUser;
    $isAdmin = false;
    if (is_object($xoopsUser)) {
        $isAdmin = $xoopsUser->isAdmin($xoopsModule->getVar('mid'));
    }
    // Add the Submit new item button
    $allowsubmit = (isset($xoopsModuleConfig['perm_submit']) && $xoopsModuleConfig['perm_submit'] == 1) ? true : false;
    $anonpost    = (isset($xoopsModuleConfig['permissions_anon_post']) && $xoopsModuleConfig['permissions_anon_post'] == 1) ? true : false;
    if ($isAdmin || ($allowsubmit && (is_object($xoopsUser) || $anonpost))) {
        $modversion['sub'][1]['name'] = _MI_PUBLISHER_SUB_SMNAME1;
        $modversion['sub'][1]['url']  = "submit.php?op=add";
    }

    // Add the Search button
    $allowsearch = (isset($xoopsModuleConfig['perm_search']) && $xoopsModuleConfig['perm_search'] == 1) ? true : false;
    if ($allowsearch) {
        $modversion['sub'][2]['name'] = _MI_PUBLISHER_SUB_SMNAME3;
        $modversion['sub'][2]['url']  = "search.php";
    }
}
// Add the Archive button
$modversion['sub'][3]['name'] = _MI_PUBLISHER_SUB_ARCHIVE;
$modversion['sub'][3]['url']  = "archive.php";

$i = 0;

++$i;
$modversion['blocks'][$i]['file']        = "items_new.php";
$modversion['blocks'][$i]['name']        = _MI_PUBLISHER_ITEMSNEW;
$modversion['blocks'][$i]['description'] = _MI_PUBLISHER_ITEMSNEW_DSC;
$modversion['blocks'][$i]['show_func']   = "publisher_items_new_show";
$modversion['blocks'][$i]['edit_func']   = "publisher_items_new_edit";
$modversion['blocks'][$i]['options']     = "0|datesub|0|5|65|none";
$modversion['blocks'][$i]['template']    = "publisher_items_new.tpl";

++$i;
$modversion['blocks'][$i]['file']        = "items_recent.php";
$modversion['blocks'][$i]['name']        = _MI_PUBLISHER_RECENTITEMS;
$modversion['blocks'][$i]['description'] = _MI_PUBLISHER_RECENTITEMS_DSC;
$modversion['blocks'][$i]['show_func']   = "publisher_items_recent_show";
$modversion['blocks'][$i]['edit_func']   = "publisher_items_recent_edit";
$modversion['blocks'][$i]['options']     = "0|datesub|5|65";
$modversion['blocks'][$i]['template']    = "publisher_items_recent.tpl";

++$i;
$modversion['blocks'][$i]['file']        = "items_spot.php";
$modversion['blocks'][$i]['name']        = _MI_PUBLISHER_ITEMSPOT;
$modversion['blocks'][$i]['description'] = _MI_PUBLISHER_ITEMSPOT_DSC;
$modversion['blocks'][$i]['show_func']   = "publisher_items_spot_show";
$modversion['blocks'][$i]['edit_func']   = "publisher_items_spot_edit";
$modversion['blocks'][$i]['options']     = "1|5|0|0|1|1|bullet|0|0";
$modversion['blocks'][$i]['template']    = "publisher_items_spot.tpl";

++$i;
$modversion['blocks'][$i]['file']        = "items_random_item.php";
$modversion['blocks'][$i]['name']        = _MI_PUBLISHER_ITEMSRANDOM_ITEM;
$modversion['blocks'][$i]['description'] = _MI_PUBLISHER_ITEMSRANDOM_ITEM_DSC;
$modversion['blocks'][$i]['show_func']   = "publisher_items_random_item_show";
$modversion['blocks'][$i]['template']    = "publisher_items_random_item.tpl";

++$i;
$modversion['blocks'][$i]['file']        = "items_menu.php";
$modversion['blocks'][$i]['name']        = _MI_PUBLISHER_ITEMSMENU;
$modversion['blocks'][$i]['description'] = _MI_PUBLISHER_ITEMSMENU_DSC;
$modversion['blocks'][$i]['show_func']   = "publisher_items_menu_show";
$modversion['blocks'][$i]['edit_func']   = "publisher_items_menu_edit";
$modversion['blocks'][$i]['options']     = "0|datesub|5";
$modversion['blocks'][$i]['template']    = "publisher_items_menu.tpl";

++$i;
$modversion['blocks'][$i]['file']        = "latest_files.php";
$modversion['blocks'][$i]['name']        = _MI_PUBLISHER_LATESTFILES;
$modversion['blocks'][$i]['description'] = _MI_PUBLISHER_LATESTFILES_DSC;
$modversion['blocks'][$i]['show_func']   = "publisher_latest_files_show";
$modversion['blocks'][$i]['edit_func']   = "publisher_latest_files_edit";
$modversion['blocks'][$i]['options']     = "0|datesub|5|0";
$modversion['blocks'][$i]['template']    = "publisher_latest_files.tpl";

++$i;
$modversion['blocks'][$i]['file']        = "date_to_date.php";
$modversion['blocks'][$i]['name']        = _MI_PUBLISHER_DATE_TO_DATE;
$modversion['blocks'][$i]['description'] = _MI_PUBLISHER_DATE_TO_DATE_DSC;
$modversion['blocks'][$i]['show_func']   = "publisher_date_to_date_show";
$modversion['blocks'][$i]['edit_func']   = "publisher_date_to_date_edit";
$modversion['blocks'][$i]['options']     = XoopsLocal::formatTimestamp(time(), 'm/j/Y') . "|" . XoopsLocal::formatTimestamp(time(), 'm/j/Y');
$modversion['blocks'][$i]['template']    = "publisher_date_to_date.tpl";

++$i;
$modversion['blocks'][$i]['file']        = "items_columns.php";
$modversion['blocks'][$i]['name']        = _MI_PUBLISHER_COLUMNS;
$modversion['blocks'][$i]['description'] = _MI_PUBLISHER_COLUMNS_DSC;
$modversion['blocks'][$i]['show_func']   = "publisher_items_columns_show";
$modversion['blocks'][$i]['edit_func']   = "publisher_items_columns_edit";
$modversion['blocks'][$i]['options']     = "2|0|4|256|normal";
$modversion['blocks'][$i]['template']    = "publisher_items_columns.tpl";

++$i;
$modversion['blocks'][$i]['file']        = "latest_news.php";
$modversion['blocks'][$i]['name']        = _MI_PUBLISHER_LATEST_NEWS;
$modversion['blocks'][$i]['description'] = _MI_PUBLISHER_LATEST_NEWS_DSC;
$modversion['blocks'][$i]['show_func']   = "publisher_latest_news_show";
$modversion['blocks'][$i]['edit_func']   = "publisher_latest_news_edit";
$modversion['blocks'][$i]['options']     = "0|6|2|300|0|0|100|30|published|1|120|120|1|dcdcdc|RIGHT|1|1|1|1|1|1|1|1|1|1|1|1|1|extended|";
$modversion['blocks'][$i]['template']    = 'publisher_latest_news.tpl';

++$i;
$modversion['blocks'][$i]['file']        = "search.php";
$modversion['blocks'][$i]['name']        = _MI_PUBLISHER_SEARCH;
$modversion['blocks'][$i]['description'] = _MI_PUBLISHER_SEARCH_DSC;
$modversion['blocks'][$i]['show_func']   = "publisher_search_show";
$modversion['blocks'][$i]['template']    = 'publisher_search_block.tpl';

++$i;
$modversion['blocks'][$i]['file']        = "category_items_sel.php";
$modversion['blocks'][$i]['name']        = _MI_PUBLISHER_CATEGORY_ITEMS_SEL;
$modversion['blocks'][$i]['description'] = _MI_PUBLISHER_CATEGORY_ITEMS_SEL_DSC;
$modversion['blocks'][$i]['show_func']   = "publisher_category_items_sel_show";
$modversion['blocks'][$i]['edit_func']   = "publisher_category_items_sel_edit";
$modversion['blocks'][$i]['options']     = "0|datesub|5|65";
$modversion['blocks'][$i]['template']    = "publisher_category_items_sel.tpl";

// Templates
$i = 0;

++$i;
$modversion['templates'][$i]['file']        = 'publisher_header.tpl';
$modversion['templates'][$i]['description'] = _MI_PUBLISHER_HEADER_DSC;

++$i;
$modversion['templates'][$i]['file']        = 'publisher_footer.tpl';
$modversion['templates'][$i]['description'] = _MI_PUBLISHER_FOOTER_DSC;

++$i;
$modversion['templates'][$i]['file']        = 'publisher_singleitem.tpl';
$modversion['templates'][$i]['description'] = _MI_PUBLISHER_SINGLEITEM_DSC;

++$i;
$modversion['templates'][$i]['file']        = 'publisher_categories_table.tpl';
$modversion['templates'][$i]['description'] = _MI_PUBLISHER_CATEGORIES_TABLE_DSC;

++$i;
$modversion['templates'][$i]['file']        = 'publisher_display_list.tpl';
$modversion['templates'][$i]['description'] = _MI_PUBLISHER_DISPLAY_LIST_DSC;

++$i;
$modversion['templates'][$i]['file']        = 'publisher_display_summary.tpl';
$modversion['templates'][$i]['description'] = _MI_PUBLISHER_DISPLAY_SUMMARY_DSC;

++$i;
$modversion['templates'][$i]['file']        = 'publisher_display_full.tpl';
$modversion['templates'][$i]['description'] = _MI_PUBLISHER_DISPLAY_FULL_DSC;

++$i;
$modversion['templates'][$i]['file']        = 'publisher_display_wfsection.tpl';
$modversion['templates'][$i]['description'] = _MI_PUBLISHER_DISPLAY_WFSECTION_DSC;

++$i;
$modversion['templates'][$i]['file']        = 'publisher_item.tpl';
$modversion['templates'][$i]['description'] = _MI_PUBLISHER_ITEM_DSC;

++$i;
$modversion['templates'][$i]['file']        = 'publisher_submit.tpl';
$modversion['templates'][$i]['description'] = _MI_PUBLISHER_SUBMIT_DSC;

++$i;
$modversion['templates'][$i]['file']        = 'publisher_singleitem_block.tpl';
$modversion['templates'][$i]['description'] = _MI_PUBLISHER_SINGLEITEM_BLOCK_DSC;

++$i;
$modversion['templates'][$i]['file']        = 'publisher_print.tpl';
$modversion['templates'][$i]['description'] = _MI_PUBLISHER_PRINT_DSC;

++$i;
$modversion['templates'][$i]['file']        = 'publisher_rss.tpl';
$modversion['templates'][$i]['description'] = _MI_PUBLISHER_RSS_DSC;

++$i;
$modversion['templates'][$i]['file']        = 'publisher_addfile.tpl';
$modversion['templates'][$i]['description'] = _MI_PUBLISHER_ADDFILE_DSC;

++$i;
$modversion['templates'][$i]['file']        = 'publisher_search.tpl';
$modversion['templates'][$i]['description'] = _MI_PUBLISHER_SEARCH_DSC;

++$i;
$modversion['templates'][$i]['file']        = 'publisher_author_items.tpl';
$modversion['templates'][$i]['description'] = _MI_PUBLISHER_AUTHOR_ITEMS_DSC;

++$i;
$modversion['templates'][$i]['file']        = 'publisher_archive.tpl';
$modversion['templates'][$i]['description'] = _MI_PUBLISHER_ARCHIVE__DSC;

// Config categories
$i                                             = 0;
$modversion['configcat']['seo']['name']        = _MI_PUBLISHER_CONFCAT_SEO;
$modversion['configcat']['seo']['description'] = _MI_PUBLISHER_CONFCAT_SEO_DSC;

++$i;
$modversion['configcat']['indexcat']['name']        = _MI_PUBLISHER_CONFCAT_INDEXCAT;
$modversion['configcat']['indexcat']['description'] = _MI_PUBLISHER_CONFCAT_INDEXCAT_DSC;

++$i;
$modversion['configcat']['index']['name']        = _MI_PUBLISHER_CONFCAT_INDEX;
$modversion['configcat']['index']['description'] = _MI_PUBLISHER_CONFCAT_INDEX_DSC;

++$i;
$modversion['configcat']['category']['name']        = _MI_PUBLISHER_CONFCAT_CATEGORY;
$modversion['configcat']['category']['description'] = _MI_PUBLISHER_CONFCAT_CATEGORY_DSC;

++$i;
$modversion['configcat']['item']['name']        = _MI_PUBLISHER_CONFCAT_ITEM;
$modversion['configcat']['item']['description'] = _MI_PUBLISHER_CONFCAT_ITEM_DSC;

++$i;
$modversion['configcat']['print']['name']        = _MI_PUBLISHER_CONFCAT_PRINT;
$modversion['configcat']['print']['description'] = _MI_PUBLISHER_CONFCAT_PRINT_DSC;

++$i;
$modversion['configcat']['search']['name']        = _MI_PUBLISHER_CONFCAT_SEARCH;
$modversion['configcat']['search']['description'] = _MI_PUBLISHER_CONFCAT_SEARCH_DSC;

++$i;
$modversion['configcat']['submit']['name']        = _MI_PUBLISHER_CONFCAT_SUBMIT;
$modversion['configcat']['submit']['description'] = _MI_PUBLISHER_CONFCAT_SUBMIT_DSC;

++$i;
$modversion['configcat']['permissions']['name']        = _MI_PUBLISHER_CONFCAT_PERMISSIONS;
$modversion['configcat']['permissions']['description'] = _MI_PUBLISHER_CONFCAT_PERMISSIONS_DSC;

++$i;
$modversion['configcat']['format']['name']        = _MI_PUBLISHER_CONFCAT_FORMAT;
$modversion['configcat']['format']['description'] = _MI_PUBLISHER_CONFCAT_FORMAT_DSC;

// Config Settings (only for modules that need config settings generated automatically)
$i = 0;

################### SEO ####################
++$i;
$modversion['config'][$i]['name']        = 'seo_url_rewrite';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_URL_REWRITE';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_URL_REWRITE_DSC';
$modversion['config'][$i]['formtype']    = 'select';
$modversion['config'][$i]['valuetype']   = 'text';
$modversion['config'][$i]['default']     = 'none';
$modversion['config'][$i]['options']     = array(
    _MI_PUBLISHER_URL_REWRITE_NONE     => 'none',
    _MI_PUBLISHER_URL_REWRITE_PATHINFO => 'path-info'
);

// Is performing module install/update?
$isModuleAction = (!empty($_POST["fct"]) && "modulesadmin" == $_POST["fct"]) ? true : false;
if ($isModuleAction && (in_array(php_sapi_name(), array("apache", "apache2handler", "cgi-fcgi")))) {
    $modversion['config'][$i]['options'][_MI_PUBLISHER_URL_REWRITE_HTACCESS] = 'htaccess';
}
$modversion['config'][$i]['category'] = 'seo';

++$i;
$modversion['config'][$i]['name']        = 'seo_module_name';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_SEOMODNAME';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_SEOMODNAMEDSC';
$modversion['config'][$i]['formtype']    = 'textbox';
$modversion['config'][$i]['valuetype']   = 'text';
$modversion['config'][$i]['default']     = $modversion['dirname'];
$modversion['config'][$i]['category']    = 'seo';

++$i;
$modversion['config'][$i]['name']        = 'seo_meta_keywords';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_SEO_METAKEYWORDS';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_SEO_METAKEYWORDS_DSC';
$modversion['config'][$i]['formtype']    = 'textbox';
$modversion['config'][$i]['valuetype']   = 'text';
$modversion['config'][$i]['default']     = '';
$modversion['config'][$i]['category']    = 'seo';

################### INDEX PAGE ####################
++$i;
$modversion['config'][$i]['name']        = 'index_title_and_welcome';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_WELCOME';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_WELCOMEDSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 1;
$modversion['config'][$i]['category']    = 'index';

++$i;
$modversion['config'][$i]['name']        = 'index_welcome_msg';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_INDEXMSG';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_INDEXMSGDSC';
$modversion['config'][$i]['formtype']    = 'textarea';
$modversion['config'][$i]['valuetype']   = 'text';
$modversion['config'][$i]['default']     = _MI_PUBLISHER_INDEXMSGDEF;
$modversion['config'][$i]['category']    = 'index';

++$i;
$modversion['config'][$i]['name']        = 'index_display_last_items';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_LASTITEMS';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_LASTITEMSDSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 1;
$modversion['config'][$i]['category']    = 'index';

++$i;
$modversion['config'][$i]['name']        = 'index_footer';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_INDEXFOOTER';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_INDEXFOOTERDSC';
$modversion['config'][$i]['formtype']    = 'textarea';
$modversion['config'][$i]['valuetype']   = 'text';
$modversion['config'][$i]['default']     = '';
$modversion['config'][$i]['category']    = 'index';

################### CATEGORY PAGE ####################
// display_categeory_summary enabled by Freeform Solutions March 21 2006
++$i;
$modversion['config'][$i]['name']        = 'cat_display_summary';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_DCS';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_DCS_DSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 1;
$modversion['config'][$i]['category']    = 'category';

++$i;
$modversion['config'][$i]['name']        = 'cat_list_image_width';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_CATLIST_IMG_W';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_CATLIST_IMG_WDSC';
$modversion['config'][$i]['formtype']    = 'textbox';
$modversion['config'][$i]['valuetype']   = 'text';
$modversion['config'][$i]['default']     = '90';
$modversion['config'][$i]['category']    = 'category';

++$i;
$modversion['config'][$i]['name']        = 'cat_main_image_width';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_CATMAINIMG_W';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_CATMAINIMG_WDSC';
$modversion['config'][$i]['formtype']    = 'textbox';
$modversion['config'][$i]['valuetype']   = 'text';
$modversion['config'][$i]['default']     = '150';
$modversion['config'][$i]['category']    = 'category';

################### ITEM PAGE ####################
++$i;
$modversion['config'][$i]['name']        = 'item_title_size';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_TITLE_SIZE';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_TITLE_SIZEDSC';
$modversion['config'][$i]['formtype']    = 'textbox';
$modversion['config'][$i]['valuetype']   = 'text';
$modversion['config'][$i]['default']     = '60';
$modversion['config'][$i]['category']    = 'item';

++$i;
$modversion['config'][$i]['name']        = 'item_disp_comment_link';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_DISCOM';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_DISCOMDSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 1;
$modversion['config'][$i]['category']    = 'item';

++$i;
$modversion['config'][$i]['name']        = 'item_disp_whowhen_link';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_WHOWHEN';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_WHOWHENDSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 1;
$modversion['config'][$i]['category']    = 'item';

++$i;
$modversion['config'][$i]['name']        = 'item_admin_hits';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_ADMINHITS';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_ADMINHITSDSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 0;
$modversion['config'][$i]['category']    = 'item';

++$i;
$modversion['config'][$i]['name']        = 'item_footer';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_ITEMFOOTER';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_ITEMFOOTERDSC';
$modversion['config'][$i]['formtype']    = 'textarea';
$modversion['config'][$i]['valuetype']   = 'text';
$modversion['config'][$i]['default']     = '';
$modversion['config'][$i]['category']    = 'item';

++$i;
$modversion['config'][$i]['name']        = 'item_other_items_type';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_OTHERITEMS';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_OTHERITEMSDSC';
$modversion['config'][$i]['formtype']    = 'select';
$modversion['config'][$i]['valuetype']   = 'text';
$modversion['config'][$i]['options']     = array(
    _MI_PUBLISHER_OTHER_ITEMS_TYPE_NONE          => 'none',
    _MI_PUBLISHER_OTHER_ITEMS_TYPE_PREVIOUS_NEXT => 'previous_next',
    _MI_PUBLISHER_OTHER_ITEMS_TYPE_ALL           => 'all'
);
$modversion['config'][$i]['default']     = 'previous_next';
$modversion['config'][$i]['category']    = 'item';

################### INDEX AND CATEGORIES ####################
++$i;
$modversion['config'][$i]['name']        = 'idxcat_show_subcats';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_SHOW_SUBCATS';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_SHOW_SUBCATS_DSC';
$modversion['config'][$i]['formtype']    = 'select';
$modversion['config'][$i]['valuetype']   = 'text';
$modversion['config'][$i]['default']     = 'all';
$modversion['config'][$i]['options']     = array(
    _MI_PUBLISHER_SHOW_SUBCATS_NO       => 'no',
    _MI_PUBLISHER_SHOW_SUBCATS_NOTEMPTY => 'nonempty',
    _MI_PUBLISHER_SHOW_SUBCATS_ALL      => 'all',
    _MI_PUBLISHER_SHOW_SUBCATS_NOMAIN   => 'nomain'
);
$modversion['config'][$i]['category']    = 'indexcat';

++$i;
$modversion['config'][$i]['name']        = 'idxcat_display_last_item';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_LASTITEM';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_LASTITEMDSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 1;
$modversion['config'][$i]['category']    = 'indexcat';

++$i;
$modversion['config'][$i]['name']        = 'idxcat_last_item_size';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_LASTITSIZE';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_LASTITSIZEDSC';
$modversion['config'][$i]['formtype']    = 'textbox';
$modversion['config'][$i]['valuetype']   = 'text';
$modversion['config'][$i]['default']     = '50';
$modversion['config'][$i]['category']    = 'indexcat';

++$i;
$modversion['config'][$i]['name']        = 'idxcat_items_display_type';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_DISTYPE';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_DISTYPEDSC';
$modversion['config'][$i]['formtype']    = 'select';
$modversion['config'][$i]['valuetype']   = 'text';
$modversion['config'][$i]['options']     = array(
    _MI_PUBLISHER_DISPLAYTYPE_SUMMARY   => 'summary',
    _MI_PUBLISHER_DISPLAYTYPE_FULL      => 'full',
    _MI_PUBLISHER_DISPLAYTYPE_LIST      => 'list',
    _MI_PUBLISHER_DISPLAYTYPE_WFSECTION => 'wfsection'
);
$modversion['config'][$i]['default']     = 'summary';
$modversion['config'][$i]['category']    = 'indexcat';

++$i;
$modversion['config'][$i] ['name']       = 'idxcat_display_subcat_dsc';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_DISSBCATDSC';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_DISSBCATDSCDSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 1;
$modversion['config'][$i]['category']    = 'indexcat';

++$i;
$modversion['config'][$i]['name']        = 'idxcat_display_date_col';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_DISDATECOL';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_DISDATECOLDSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 1;
$modversion['config'][$i]['category']    = 'indexcat';

++$i;
$modversion['config'][$i]['name']        = 'idxcat_display_hits_col';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_HITSCOL';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_HITSCOLDSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 1;
$modversion['config'][$i]['category']    = 'indexcat';

++$i;
$modversion['config'][$i]['name']        = 'idxcat_show_rss_link';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_SHOW_RSS';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_SHOW_RSSDSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 1;
$modversion['config'][$i]['category']    = 'indexcat';

++$i;
$modversion['config'][$i]['name']        = 'idxcat_collaps_heading';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_COLLHEAD';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_COLLHEADDSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 1;
$modversion['config'][$i]['category']    = 'indexcat';

++$i;
$modversion['config'][$i]['name']        = 'idxcat_cat_perpage';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_CATPERPAGE';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_CATPERPAGEDSC';
$modversion['config'][$i]['formtype']    = 'select';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 15;
$modversion['config'][$i]['options']     = array('5' => 5, '10' => 10, '15' => 15, '20' => 20, '25' => 25, '30' => 30, '50' => 50);
$modversion['config'][$i]['category']    = 'indexcat';

++$i;
$modversion['config'][$i]['name']        = 'idxcat_perpage';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_PERPAGE';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_PERPAGEDSC';
$modversion['config'][$i]['formtype']    = 'select';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 15;
$modversion['config'][$i]['options']     = array('5' => 5, '10' => 10, '15' => 15, '20' => 20, '25' => 25, '30' => 30, '50' => 50);
$modversion['config'][$i]['category']    = 'indexcat';

++$i;
$modversion['config'][$i]['name']        = 'idxcat_index_perpage';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_PERPAGEINDEX';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_PERPAGEINDEXDSC';
$modversion['config'][$i]['formtype']    = 'select';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 15;
$modversion['config'][$i]['options']     = array('5' => 5, '10' => 10, '15' => 15, '20' => 20, '25' => 25, '30' => 30, '50' => 50);
$modversion['config'][$i]['category']    = 'indexcat';

++$i;
$modversion['config'][$i]['name']        = 'idxcat_partial_view_text';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_PV_TEXT';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_PV_TEXTDSC';
$modversion['config'][$i]['formtype']    = 'textarea';
$modversion['config'][$i]['valuetype']   = 'text';
$modversion['config'][$i]['default']     = _MI_PUBLISHER_PV_TEXT_DEF;
$modversion['config'][$i]['category']    = 'indexcat';

++$i;
$modversion['config'][$i]['name']        = 'idxcat_display_art_count';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_ARTCOUNT';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_ARTCOUNTDSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 0;
$modversion['config'][$i]['category']    = 'indexcat';

################### PRINT ####################
++$i;
$modversion['config'][$i]['name']        = 'print_header';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_HEADERPRINT';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_HEADERPRINTDSC';
$modversion['config'][$i]['formtype']    = 'textarea';
$modversion['config'][$i]['valuetype']   = 'text';
$modversion['config'][$i]['default']     = '';
$modversion['config'][$i]['category']    = 'print';

++$i;
$modversion['config'][$i]['name']        = 'print_logourl';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_PRINTLOGOURL';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_PRINTLOGOURLDSC';
$modversion['config'][$i]['formtype']    = 'textbox';
$modversion['config'][$i]['valuetype']   = 'text';
$modversion['config'][$i]['default']     = XOOPS_URL . '/images/logo.gif';
$modversion['config'][$i]['category']    = 'print';

++$i;
$modversion['config'][$i]['name']        = 'print_footer';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_FOOTERPRINT';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_FOOTERPRINTDSC';
$modversion['config'][$i]['formtype']    = 'select';
$modversion['config'][$i]['valuetype']   = 'text';
$modversion['config'][$i]['default']     = 'item footer';
$modversion['config'][$i]['options']     = array(
    _MI_PUBLISHER_ITEMFOOTER_SEL  => 'item footer',
    _MI_PUBLISHER_INDEXFOOTER_SEL => 'index footer',
    _MI_PUBLISHER_BOTH_FOOTERS    => 'both',
    _MI_PUBLISHER_NO_FOOTERS      => 'none'
);
$modversion['config'][$i]['category']    = 'print';

################### FORMAT ####################
++$i;
$modversion['config'][$i]['name']        = 'format_date';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_DATEFORMAT';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_DATEFORMATDSC';
$modversion['config'][$i]['formtype']    = 'textbox';
$modversion['config'][$i]['valuetype']   = 'text';
$modversion['config'][$i]['default']     = 'd-M-Y H:i';
$modversion['config'][$i]['category']    = 'format';

++$i;
$modversion['config'][$i]['name']        = 'format_order_by';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_ORDERBY';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_ORDERBYDSC';
$modversion['config'][$i]['formtype']    = 'select';
$modversion['config'][$i]['valuetype']   = 'text';
$modversion['config'][$i]['options']     = array(
    _MI_PUBLISHER_ORDERBY_TITLE  => 'title',
    _MI_PUBLISHER_ORDERBY_DATE   => 'date',
    _MI_PUBLISHER_ORDERBY_WEIGHT => 'weight'
);
$modversion['config'][$i]['default']     = 'date';
$modversion['config'][$i]['category']    = 'format';

++$i;
$modversion['config'][$i]['name']        = 'format_image_nav';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_IMAGENAV';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_IMAGENAVDSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 0;
$modversion['config'][$i]['category']    = 'format';

++$i;
$modversion['config'][$i]['name']        = 'format_realname';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_USEREALNAME';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_USEREALNAMEDSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 0;
$modversion['config'][$i]['category']    = 'format';

++$i;
$modversion['config'][$i]['name']        = 'format_highlight_color';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_HLCOLOR';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_HLCOLORDSC';
$modversion['config'][$i]['formtype']    = 'textbox';
$modversion['config'][$i]['valuetype']   = 'text';
$modversion['config'][$i]['default']     = '#FFFF80';
$modversion['config'][$i]['category']    = 'format';

++$i;
$modversion['config'][$i]['name']        = 'format_linked_path';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_LINKPATH';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_LINKPATHDSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 1;
$modversion['config'][$i]['category']    = 'format';

++$i;
$modversion['config'][$i]['name']        = 'format_breadcrumb_modname';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_BCRUMB';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_BCRUMBDSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 1;
$modversion['config'][$i]['category']    = 'format';

################### SEARCH ####################
++$i;
$modversion['config'][$i]['name']        = 'search_cat_path';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_PATHSEARCH';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_PATHSEARCHDSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 0;
$modversion['config'][$i]['category']    = 'search';

################### SUBMIT ####################
++$i;
$modversion['config'][$i]['name']        = 'submit_intro_msg';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_SUBMITMSG';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_SUBMITMSGDSC';
$modversion['config'][$i]['formtype']    = 'textarea';
$modversion['config'][$i]['valuetype']   = 'text';
$modversion['config'][$i]['default']     = _MI_PUBLISHER_SUBMITMSGDEF;
$modversion['config'][$i]['category']    = 'submit';

xoops_load('XoopsEditorHandler');
$editor_handler = XoopsEditorHandler::getInstance();
++$i;
$modversion['config'][$i]['name']        = 'submit_editor';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_EDITOR';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_EDITOR_DSC';
$modversion['config'][$i]['formtype']    = 'select';
$modversion['config'][$i]['valuetype']   = 'text';
$modversion['config'][$i]['options']     = array_flip($editor_handler->getList());
$modversion['config'][$i]['default']     = 'dhtmltextarea';
$modversion['config'][$i]['category']    = 'submit';

++$i;
$modversion['config'][$i]['name']        = 'submit_editor_rows';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_EDITOR_ROWS';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_EDITOR_ROWS_DSC';
$modversion['config'][$i]['formtype']    = 'textbox';
$modversion['config'][$i]['valuetype']   = 'text';
$modversion['config'][$i]['default']     = '35';
$modversion['config'][$i]['category']    = 'submit';

++$i;
$modversion['config'][$i]['name']        = 'submit_editor_cols';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_EDITOR_COLS';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_EDITOR_COlS_DSC';
$modversion['config'][$i]['formtype']    = 'textbox';
$modversion['config'][$i]['valuetype']   = 'text';
$modversion['config'][$i]['default']     = '60';
$modversion['config'][$i]['category']    = 'submit';

++$i;
$modversion['config'][$i]['name']        = 'submit_editor_width';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_EDITOR_WIDTH';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_EDITOR_WIDTH_DSC';
$modversion['config'][$i]['formtype']    = 'textbox';
$modversion['config'][$i]['valuetype']   = 'text';
$modversion['config'][$i]['default']     = '100%';
$modversion['config'][$i]['category']    = 'submit';

++$i;
$modversion['config'][$i]['name']        = 'submit_editor_height';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_EDITOR_HEIGHT';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_EDITOR_HEIGHT_DSC';
$modversion['config'][$i]['formtype']    = 'textbox';
$modversion['config'][$i]['valuetype']   = 'text';
$modversion['config'][$i]['default']     = '400px';
$modversion['config'][$i]['category']    = 'submit';

++$i;
$modversion['config'][$i]['name']        = 'submit_status';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_FORM_STATUS';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_FORM_STATUS_DSC';
$modversion['config'][$i]['formtype']    = 'select';
$modversion['config'][$i]['valuetype']   = 'text';
$modversion['config'][$i]['options']     = array(
    _MI_PUBLISHER_PUBLISHED => PublisherConstants::_PUBLISHER_STATUS_PUBLISHED,
    _MI_PUBLISHER_OFFLINE   => PublisherConstants::_PUBLISHER_STATUS_OFFLINE,
    _MI_PUBLISHER_SUBMITTED => PublisherConstants::_PUBLISHER_STATUS_SUBMITTED,
    _MI_PUBLISHER_REJECTED  => PublisherConstants::_PUBLISHER_STATUS_REJECTED
);
$modversion['config'][$i]['default']     = PublisherConstants::_PUBLISHER_STATUS_SUBMITTED;
$modversion['config'][$i]['category']    = 'submit';

++$i;
$modversion['config'][$i]['name']        = 'submit_allowcomments';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_FORM_ALLOWCOMMENTS';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_FORM_ALLOWCOMMENTS_DSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 1;
$modversion['config'][$i]['category']    = 'submit';

++$i;
$modversion['config'][$i]['name']        = 'submit_dohtml';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_FORM_DOHTML';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_FORM_DOHTML_DSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 1;
$modversion['config'][$i]['category']    = 'submit';

++$i;
$modversion['config'][$i]['name']        = 'submit_dosmiley';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_FORM_DOSMILEY';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_FORM_DOSMILEY_DSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 1;
$modversion['config'][$i]['category']    = 'submit';

++$i;
$modversion['config'][$i]['name']        = 'submit_doxcode';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_FORM_DOXCODE';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_FORM_DOXCODE_DSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 1;
$modversion['config'][$i]['category']    = 'submit';

++$i;
$modversion['config'][$i]['name']        = 'submit_doimage';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_FORM_DOIMAGE';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_FORM_DOIMAGE_DSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 1;
$modversion['config'][$i]['category']    = 'submit';

++$i;
$modversion['config'][$i]['name']        = 'submit_dobr';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_FORM_DOBR';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_FORM_DOBR_DSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 1;
$modversion['config'][$i]['category']    = 'submit';

################### PERMISSIONS ####################
++$i;
$modversion['config'][$i]['name']        = 'perm_submit';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_ALLOWSUBMIT';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_ALLOWSUBMITDSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 0;
$modversion['config'][$i]['category']    = 'permissions';

++$i;
$modversion['config'][$i]['name']        = 'perm_edit';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_ALLOWEDIT';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_ALLOWEDITDSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 0;
$modversion['config'][$i]['category']    = 'permissions';

++$i;
$modversion['config'][$i]['name']        = 'perm_delete';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_ALLOWDELETE';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_ALLOWDELETEDSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 0;
$modversion['config'][$i]['category']    = 'permissions';

++$i;
$modversion['config'][$i]['name']        = 'perm_anon_submit';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_ANONPOST';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_ANONPOSTDSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 0;
$modversion['config'][$i]['category']    = 'permissions';

++$i;
$modversion['config'][$i]['name']        = 'perm_upload';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_UPLOAD';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_UPLOADDSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 1;
$modversion['config'][$i]['category']    = 'permissions';

++$i;
$modversion['config'][$i]['name']        = 'perm_clone';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_CLONE';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_CLONEDSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 1;
$modversion['config'][$i]['category']    = 'permissions';

++$i;
$modversion['config'][$i]['name']        = 'perm_rating';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_ALLOWRATING';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_ALLOWRATING_DSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 1;
$modversion['config'][$i]['category']    = 'permissions';

++$i;
$modversion['config'][$i]['name']        = 'perm_search';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_ALLOWSEARCH';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_ALLOWSEARCH_DSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 1;
$modversion['config'][$i]['category']    = 'permissions';

++$i;
$modversion['config'][$i]['name']        = 'perm_author_items';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_ALLOW_AUTHOR_ITEMS';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_ALLOW_AUTHOR_ITEMS_DSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 1;
$modversion['config'][$i]['category']    = 'permissions';

++$i;
$modversion['config'][$i]['name']        = 'perm_com_art_level';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_COMMENTS';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_COMMENTSDSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 1;
$modversion['config'][$i]['category']    = 'permissions';

++$i;
$modversion['config'][$i]['name']        = 'perm_autoapprove';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_AUTOAPP';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_AUTOAPPDSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 0;
$modversion['config'][$i]['category']    = 'permissions';

################### OTHERS ####################
++$i;
$modversion['config'][$i]['name']        = 'display_breadcrumb';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_DISPBREAD';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_DISPBREADDSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 1;

++$i;
$modversion['config'][$i]['name']        = 'display_pdf';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_DISPLAY_PDF';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_DISPLAY_PDF_DSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 1;

++$i;
$modversion['config'][$i]['name']        = 'maximum_filesize';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_MAX_SIZE';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_MAX_SIZEDSC';
$modversion['config'][$i]['formtype']    = 'textbox';
$modversion['config'][$i]['valuetype']   = 'text';
$modversion['config'][$i]['default']     = '1000000';

++$i;
$modversion['config'][$i]['name']        = 'maximum_image_width';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_MAX_WIDTH';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_MAX_WIDTHDSC';
$modversion['config'][$i]['formtype']    = 'textbox';
$modversion['config'][$i]['valuetype']   = 'text';
$modversion['config'][$i]['default']     = '800';

++$i;
$modversion['config'][$i]['name']        = 'maximum_image_height';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_MAX_HEIGHT';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_MAX_HEIGHTDSC';
$modversion['config'][$i]['formtype']    = 'textbox';
$modversion['config'][$i]['valuetype']   = 'text';
$modversion['config'][$i]['default']     = '800';

########### ADDED in final #############
++$i;
$modversion['config'][$i]['name']        = 'item_disp_blocks_summary';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_DISP_BLOCK_SUM';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_DISP_BLOCK_SUM_DSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 0;
$modversion['config'][$i]['category']    = 'item';

++$i;
$modversion['config'][$i]['name']        = 'index_disp_subtitle';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_DISP_INDEX_SUB';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_DISP_INDEX_SUB_DSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 0;
$modversion['config'][$i]['category']    = 'index';

++$i;
$modversion['config'][$i]['name']        = 'cat_disp_subtitle';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_DISP_CAT_SUB';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_DISP_CAT_SUB_DSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 0;
$modversion['config'][$i]['category']    = 'category';

++$i;
$modversion['config'][$i]['name']        = 'item_disp_subtitle';
$modversion['config'][$i]['title']       = '_MI_PUBLISHER_DISP_ITEM_SUB';
$modversion['config'][$i]['description'] = '_MI_PUBLISHER_DISP_ITEM_SUB_DSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 1;
$modversion['config'][$i]['category']    = 'item';

// Comments
$modversion['hasComments']          = 1;
$modversion['comments']['itemName'] = 'itemid';
$modversion['comments']['pageName'] = 'item.php';

// Comment callback functions
$modversion['comments']['callbackFile']        = 'include/comment_functions.php';
$modversion['comments']['callback']['approve'] = 'publisher_com_approve';
$modversion['comments']['callback']['update']  = 'publisher_com_update';

// Notification
$modversion['hasNotification']             = 1;
$modversion['notification']['lookup_file'] = 'include/notification.inc.php';
$modversion['notification']['lookup_func'] = 'publisher_notify_iteminfo';

$modversion['notification']['category'][1]['name']           = 'global_item';
$modversion['notification']['category'][1]['title']          = _MI_PUBLISHER_GLOBAL_ITEM_NOTIFY;
$modversion['notification']['category'][1]['description']    = _MI_PUBLISHER_GLOBAL_ITEM_NOTIFY_DSC;
$modversion['notification']['category'][1]['subscribe_from'] = array('index.php', 'category.php', 'item.php');

$modversion['notification']['category'][2]['name']           = 'category_item';
$modversion['notification']['category'][2]['title']          = _MI_PUBLISHER_CATEGORY_ITEM_NOTIFY;
$modversion['notification']['category'][2]['description']    = _MI_PUBLISHER_CATEGORY_ITEM_NOTIFY_DSC;
$modversion['notification']['category'][2]['subscribe_from'] = array('index.php', 'category.php', 'item.php');
$modversion['notification']['category'][2]['item_name']      = 'categoryid';
$modversion['notification']['category'][2]['allow_bookmark'] = 1;

$modversion['notification']['category'][3]['name']           = 'item';
$modversion['notification']['category'][3]['title']          = _MI_PUBLISHER_ITEM_NOTIFY;
$modversion['notification']['category'][3]['description']    = _MI_PUBLISHER_ITEM_NOTIFY_DSC;
$modversion['notification']['category'][3]['subscribe_from'] = array('item.php');
$modversion['notification']['category'][3]['item_name']      = 'itemid';
$modversion['notification']['category'][3]['allow_bookmark'] = 1;

$modversion['notification']['event'][1]['name']          = 'category_created';
$modversion['notification']['event'][1]['category']      = 'global_item';
$modversion['notification']['event'][1]['title']         = _MI_PUBLISHER_GLOBAL_ITEM_CATEGORY_CREATED_NOTIFY;
$modversion['notification']['event'][1]['caption']       = _MI_PUBLISHER_GLOBAL_ITEM_CATEGORY_CREATED_NOTIFY_CAP;
$modversion['notification']['event'][1]['description']   = _MI_PUBLISHER_GLOBAL_ITEM_CATEGORY_CREATED_NOTIFY_DSC;
$modversion['notification']['event'][1]['mail_template'] = 'global_item_category_created';
$modversion['notification']['event'][1]['mail_subject']  = _MI_PUBLISHER_GLOBAL_ITEM_CATEGORY_CREATED_NOTIFY_SBJ;

$modversion['notification']['event'][2]['name']          = 'submitted';
$modversion['notification']['event'][2]['category']      = 'global_item';
$modversion['notification']['event'][2]['admin_only']    = 1;
$modversion['notification']['event'][2]['title']         = _MI_PUBLISHER_GLOBAL_ITEM_SUBMITTED_NOTIFY;
$modversion['notification']['event'][2]['caption']       = _MI_PUBLISHER_GLOBAL_ITEM_SUBMITTED_NOTIFY_CAP;
$modversion['notification']['event'][2]['description']   = _MI_PUBLISHER_GLOBAL_ITEM_SUBMITTED_NOTIFY_DSC;
$modversion['notification']['event'][2]['mail_template'] = 'global_item_submitted';
$modversion['notification']['event'][2]['mail_subject']  = _MI_PUBLISHER_GLOBAL_ITEM_SUBMITTED_NOTIFY_SBJ;

$modversion['notification']['event'][3]['name']          = 'published';
$modversion['notification']['event'][3]['category']      = 'global_item';
$modversion['notification']['event'][3]['title']         = _MI_PUBLISHER_GLOBAL_ITEM_PUBLISHED_NOTIFY;
$modversion['notification']['event'][3]['caption']       = _MI_PUBLISHER_GLOBAL_ITEM_PUBLISHED_NOTIFY_CAP;
$modversion['notification']['event'][3]['description']   = _MI_PUBLISHER_GLOBAL_ITEM_PUBLISHED_NOTIFY_DSC;
$modversion['notification']['event'][3]['mail_template'] = 'global_item_published';
$modversion['notification']['event'][3]['mail_subject']  = _MI_PUBLISHER_GLOBAL_ITEM_PUBLISHED_NOTIFY_SBJ;

$modversion['notification']['event'][4]['name']          = 'submitted';
$modversion['notification']['event'][4]['category']      = 'category_item';
$modversion['notification']['event'][4]['admin_only']    = 1;
$modversion['notification']['event'][4]['title']         = _MI_PUBLISHER_CATEGORY_ITEM_SUBMITTED_NOTIFY;
$modversion['notification']['event'][4]['caption']       = _MI_PUBLISHER_CATEGORY_ITEM_SUBMITTED_NOTIFY_CAP;
$modversion['notification']['event'][4]['description']   = _MI_PUBLISHER_CATEGORY_ITEM_SUBMITTED_NOTIFY_DSC;
$modversion['notification']['event'][4]['mail_template'] = 'category_item_submitted';
$modversion['notification']['event'][4]['mail_subject']  = _MI_PUBLISHER_CATEGORY_ITEM_SUBMITTED_NOTIFY_SBJ;

$modversion['notification']['event'][5]['name']          = 'published';
$modversion['notification']['event'][5]['category']      = 'category_item';
$modversion['notification']['event'][5]['title']         = _MI_PUBLISHER_CATEGORY_ITEM_PUBLISHED_NOTIFY;
$modversion['notification']['event'][5]['caption']       = _MI_PUBLISHER_CATEGORY_ITEM_PUBLISHED_NOTIFY_CAP;
$modversion['notification']['event'][5]['description']   = _MI_PUBLISHER_CATEGORY_ITEM_PUBLISHED_NOTIFY_DSC;
$modversion['notification']['event'][5]['mail_template'] = 'category_item_published';
$modversion['notification']['event'][5]['mail_subject']  = _MI_PUBLISHER_CATEGORY_ITEM_PUBLISHED_NOTIFY_SBJ;

$modversion['notification']['event'][6]['name']          = 'rejected';
$modversion['notification']['event'][6]['category']      = 'item';
$modversion['notification']['event'][6]['invisible']     = 1;
$modversion['notification']['event'][6]['title']         = _MI_PUBLISHER_ITEM_REJECTED_NOTIFY;
$modversion['notification']['event'][6]['caption']       = _MI_PUBLISHER_ITEM_REJECTED_NOTIFY_CAP;
$modversion['notification']['event'][6]['description']   = _MI_PUBLISHER_ITEM_REJECTED_NOTIFY_DSC;
$modversion['notification']['event'][6]['mail_template'] = 'item_rejected';
$modversion['notification']['event'][6]['mail_subject']  = _MI_PUBLISHER_ITEM_REJECTED_NOTIFY_SBJ;

$modversion['notification']['event'][7]['name']          = 'approved';
$modversion['notification']['event'][7]['category']      = 'item';
$modversion['notification']['event'][7]['invisible']     = 1;
$modversion['notification']['event'][7]['title']         = _MI_PUBLISHER_ITEM_APPROVED_NOTIFY;
$modversion['notification']['event'][7]['caption']       = _MI_PUBLISHER_ITEM_APPROVED_NOTIFY_CAP;
$modversion['notification']['event'][7]['description']   = _MI_PUBLISHER_ITEM_APPROVED_NOTIFY_DSC;
$modversion['notification']['event'][7]['mail_template'] = 'item_approved';
$modversion['notification']['event'][7]['mail_subject']  = _MI_PUBLISHER_ITEM_APPROVED_NOTIFY_SBJ;
